on:
  push:
    branches: main

name: Build & Deploy Site
env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Cache packages (renv)
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
        
      - name: Restore packages (renv)
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Remove multiple html files
        run: Rscript -e 'knitr::knit("Distill_Quality_Control.Rmd")'
  
      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
        
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs